# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'zhangchunxin'

#google-ID: 'UA-112060364-1'

menu:
- {name: '生活', path: 'menu', url: 'life.html'}
- {name: '技术', path: 'menu', url: 'tech.html'}
- {name: '爱', path: 'menu', url: 'love.html'}
- {name: '归档', path: 'menu', url: 'archive.html'}
- {name: '关于我', path: 'menu', url: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'weibo', link: 'https://weibo.com/aqxyjay'}
- {icon: 'github', link: 'https://www.github.com/aqxyjay'}
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
# - {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'envelope', link: 'mailto:me@zhangchunxin.com'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: '下一页'
  previous_page: '上一页'

sharing_button_prompt: '点击分享:'

related_posts: '看看其他的:'

post_date_prefix: '发布于'
